language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=tile_stitcher -m py.test -s
after_success:
  - coveralls
sudo: false
